
global:
  scrape_interval: 5s

scrape_configs:

# The "tasks." prefix allows to resolve the IP addresses of the service instance
# containers instead of just the Virtual IP of the (logical) service

- job_name: hono-service-auth
  metrics_path: /prometheus
  dns_sd_configs:
  - names:
      - tasks.hono-service-auth.hono
    type: A
    port: ${prometheus.scraping.port}
    refresh_interval: 10s

- job_name: hono-service-device-registry
  metrics_path: /prometheus
  dns_sd_configs:
  - names:
      - tasks.hono-service-device-registry.hono
    type: A
    port: ${prometheus.scraping.port}
    refresh_interval: 10s

- job_name: hono-adapter-amqp-vertx
  metrics_path: /prometheus
  dns_sd_configs:
  - names:
      - tasks.hono-adapter-amqp-vertx.hono
    type: A
    port: ${prometheus.scraping.port}
    refresh_interval: 10s

- job_name: hono-adapter-http-vertx
  metrics_path: /prometheus
  dns_sd_configs:
  - names:
      - tasks.hono-adapter-http-vertx.hono
    type: A
    port: ${prometheus.scraping.port}
    refresh_interval: 10s

- job_name: hono-adapter-mqtt-vertx
  metrics_path: /prometheus
  dns_sd_configs:
  - names:
      - tasks.hono-adapter-mqtt-vertx.hono
    type: A
    port: ${prometheus.scraping.port}
    refresh_interval: 10s

- job_name: hono-adapter-kura
  metrics_path: /prometheus
  dns_sd_configs:
  - names:
      - tasks.hono-adapter-kura.hono
    type: A
    port: ${prometheus.scraping.port}
    refresh_interval: 10s

- job_name: hono-adapter-coap-vertx
  metrics_path: /prometheus
  dns_sd_configs:
  - names:
      - tasks.hono-adapter-coap-vertx.hono
    type: A
    port: ${prometheus.scraping.port}
    refresh_interval: 10s
