spec:
  template:
    spec:
      volumes:
      - name: config
        secret:
          secretName: ${project.artifactId}-conf
      containers:
      - image: ${artemis.image.name}
        command:
        - /opt/artemis/bin/artemis
        - run
        - xml:/etc/hono/artemis-bootstrap.xml
        env:
        - name: ARTEMIS_CONFIGURATION
          value: /etc/hono
        volumeMounts:
        - name: config
          mountPath: /etc/hono
          readOnly: true
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          tcpSocket:
            port: 5671
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 9
          timeoutSeconds: 1
          tcpSocket:
            port: 5671
