hono:
  downstream:
    host: localhost
    port: 5672
    name: hono-server
  maxInstances: 0
  registration:
    filename: /home/hono/registration/device-identities.json
  singleTenant: false
  server:
    bindaddress: 127.0.0.1
    port: 5672
