hono:
  downstream:
    host: localhost
    port: 5672
    name: hono-server
  registration:
    filename: /home/hono/registration/device-identities.json
  server:
    bindAddress: 127.0.0.1
    port: 5672
    maxInstances: 0
    singleTenant: false
