---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: hono-service-device-registry
    provider: fabric8
    version: 0.7-M1-SNAPSHOT
    group: org.eclipse.hono
  name: registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
