---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: AMQP_Messaging_Network
    version: "${project.version}"
    group: ${project.groupId}
  name: hono-artemis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AMQP_Messaging_Network
      role: broker
      group: ${project.groupId}
  template:
    metadata:
      labels:
        app: AMQP_Messaging_Network
        role: broker
        version: "${project.version}"
        group: ${project.groupId}
    spec:
      containers:
      - command:
        - /opt/artemis/bin/artemis
        - run
        - xml:/etc/hono/artemis-bootstrap.xml
        env:
        - name: ARTEMIS_CONFIGURATION
          value: /etc/hono
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ${artemis.image.name}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 9
          tcpSocket:
            port: 5671
          timeoutSeconds: 1
        name: eclipse-hono-artemis
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          tcpSocket:
            port: 5671
          timeoutSeconds: 1
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /etc/hono
          name: config
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: hono-artemis-conf
