#
# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
hono:
  app:
    maxInstances: 1
  healthCheck:
    port: ${vertx.health.port}
    bindAddress: 0.0.0.0
    keyPath: /run/secrets/hono.eclipse.org-key.pem
    certPath: /run/secrets/hono.eclipse.org-cert.pem
  coap:
    bindAddress: 0.0.0.0
    port: 5684
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
    keyPath: /run/secrets/hono.eclipse.org-key.pem
    certPath: /run/secrets/hono.eclipse.org-cert.pem
    tenantIdleTimeout: 1h
  messaging:
    name: 'Hono AMQP Adapter'
    amqpHostname: hono-internal
    host: ${hono.amqp-network.service}${service.suffix}
    port: 5673
  registration:
    name: 'Hono AMQP Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5672
    credentialsPath: /run/secrets/coap-adapter.credentials
  credentials:
    name: 'Hono AMQP Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5672
    credentialsPath: /run/secrets/coap-adapter.credentials
  tenant:
    name: 'Hono AMQP Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5672
    credentialsPath: /run/secrets/coap-adapter.credentials
  deviceConnection:
    name: 'Hono AMQP Adapter'
    host: ${hono.registration.service}${service.suffix}
    port: 5672
    credentialsPath: /run/secrets/coap-adapter.credentials
  command:
    name: 'Hono AMQP Adapter'
    amqpHostname: hono-internal
    host: ${hono.amqp-network.service}${service.suffix}
    port: 5673
