#
# Copyright (c) 2019 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: v1
# Version of the Helm chart, by default, this will be the Maven project version
version: ${project.version}
# Version of the application being deployed by the chart
appVersion: ${project.version}
name: eclipse-hono
description: |
  Eclipse Hono™ provides remote service interfaces for connecting large numbers of IoT devices to a back end and
  interacting with them in a uniform way regardless of the device communication protocol.
icon: https://github.com/eclipse/hono/blob/master/logo/SVG-Tiny/HONO-Logo_Bild_s-135x125px.svg
keywords:
  - IoT
  - messaging
home: https://www.eclipse.org/hono/
sources:
  - https://github.com/eclipse/hono
